# Generated by Django 4.2.7 on 2024-11-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_invoice_test_ulr'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_old_invoice_format',
            field=models.BooleanField(default=False),
        ),
    ]
